### Save Project
POST http://localhost:8099/v1/projects
Content-Type: application/json

{
  "id": "1",
  "name": "ProjectA",
  "code": "A",
  "description": "Project A Description",
  "startDate": "2023-01-01",
  "endDate": "2023-10-01",
  "estimatedCost": 1000,
  "countryList": ["UK", "USA", "KOREA", "JAPAN"]
}

### Save Task
POST http://localhost:8099/v1/tasks
Content-Type: application/json

{
  "id": "1",
  "projectId": "1",
  "name": "Solve Math",
  "description": "Solve Math in time",
  "ownername": "KIDO",
  "cost": 3000

}

### GET Project
GET http://localhost:8099/v1/projects?id=1

### GET Task
GET http://localhost:8099/v1/tasks?id=1

### Delete Task
DELETE http://localhost:8099/v1/tasks/1

### GET findbyName
GET http://localhost:8099/v1/projects/findByName?name=ProjectA

### GET /projects/findByNameNot
GET http://localhost:8099/v1/projects/findByNameNot?name=ProjectB

### GET /projects/findByEstimatedCostGreaterThan
GET http://localhost:8099/v1/projects/findByEstimatedCostGreaterThan?cost=900

### GET /projects/findByNameLike
GET http://localhost:8099/v1/projects/findByNameLike?name=Projec

### GET /projects/findByNameRegex
GET http://localhost:8099/v1/projects/findByNameRegex?name=Pro

### GET /projects/findProjectByNameQuery
GET http://localhost:8099/v1/projects/findProjectByNameQuery?name=ProjectA

### GET /projects/findProjectNameAndCostQuery
GET http://localhost:8099/v1/projects/findProjectNameAndCostQuery?name=ProjectA&cost=1000

### GET /projects/findByEstimatedCostBetweenQuery
GET http://localhost:8099/v1/projects/findByEstimatedCostBetweenQuery?from=100&to=2000

### GET /projects/findByNameRegexQuery
GET http://localhost:8099/v1/projects/findByNameRegexQuery?name=Proje

### @GetMapping("/projects/findProjectByNameQueryWithTemplate")
GET http://localhost:8099/v1/projects/findProjectByNameQueryWithTemplate?name=ProjectA

### @GetMapping("/projects/findByEstimatedCostBetweenQueryWithTemplate")
GET http://localhost:8099/v1/projects/findByEstimatedCostBetweenQueryWithTemplate?from=100&to=2000

### @GetMapping("/projects/findByNameRegexQueryWithTemplate")
GET http://localhost:8099/v1/projects/findByNameRegexQueryWithTemplate?name=Project

### @GetMapping("/projects/upsertCostWithCriteriaTemplate/{id}/{cost}")
GET http://localhost:8099/v1/projects/upsertCostWithCriteriaTemplate/1/1900

### @GetMapping("/projects/deleteWithCriteriaTemplate/{id}")
GET http://localhost:8099/v1/projects/deleteWithCriteriaTemplate/1

### @GetMapping("/projects/findNoOfProjectsCostGreaterThan")
GET http://localhost:8099/v1/projects/findNoOfProjectsCostGreaterThan?cost=1000

### @GetMapping("/projects/findCostsGroupByStartDateForProjectsCostGreaterThan")
GET http://localhost:8099/v1/projects/findCostsGroupByStartDateForProjectsCostGreaterThan?cost=1000

### @GetMapping("/projects/findAllProjectTasks")
GET http://localhost:8099/v1/projects/findAllProjectTasks


### @GetMapping("/projects/findNameDescriptionForMatchingTerm")
GET http://localhost:8099/v1/projects/findNameDescriptionForMatchingTerm?name=Proj

### @GetMapping("/projects/findNameDescriptionForMatchingAny")
GET http://localhost:8099/v1/projects/findNameDescriptionForMatchingAny?words=Pro,Proj,Project

### @GetMapping("/projects/findNameDescriptionForMatchingPhrase")
GET http://localhost:8099/v1/projects/findNameDescriptionForMatchingPhrase?pharase=Project A Descr