### Save Project
POST http://localhost:8099/v1/projects
Content-Type: application/json

{
  "id": "1",
  "name": "ProjectA",
  "code": "A",
  "description": "Project A Description",
  "startDate": "2023-01-01",
  "endDate": "2023-10-01",
  "estimatedCost": 1000,
  "countryList": ["UK", "USA", "KOREA", "JAPAN"]
}

### Save Task
POST http://localhost:8099/v1/tasks
Content-Type: application/json

{
  "id": "1",
  "projectId": "1",
  "name": "Solve Math",
  "description": "Solve Math in time",
  "ownername": "KIDO",
  "cost": 3000

}

### GET Project
GET http://localhost:8099/v1/projects?id=1

### GET Task
GET http://localhost:8099/v1/tasks?id=1

### Delete Task
DELETE http://localhost:8099/v1/tasks/1