
server:
  port: 8099
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin1234@localhost:27017/project?authSource=admin&retryWrites=false
      replica-set-name: rs0
      repositories:
        type: auto
      ssl:
        enabled: false
      authentication-database: admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG